### ISSUE TITLE
Docker containers do not start on Ubuntu 20.10

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#1]
The _docker_ `simulator` container fails to start on Ubuntu 20.10:
```
$ docker run --interactive --publish 8000:8000 --publish 60000:60000/udp --name simulator --rm simulator
/bin/sh: /opt/uhppote/uhppote-simulator: not found
```

#### Notes

1. [Go-compiled binary won't run in an alpine docker container on Ubuntu host](https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host)

2. [Golang and docker](http://kefblog.com/2017-07-04/Golang-ang-docker)

3. [node-red-contrib-uhppoted:listen node Problem](https://github.com/uhppoted/node-red-contrib-uhppoted/issues/3)

**Comment by twystd** [comment]
Verified - docker containers start and run on Ubuntu 20.10
