### ISSUE TITLE
Rework all services/daemons to wait for multi-user/network

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#19]
Ref. [Handling of lockfile on crash/restart](https://github.com/uhppoted/uhppoted-tunnel/issues/7)

- [x] uhppoted-rest
- [x] uhppoted-mqtt
- [x] uhppoted-tunnel
- [x] uhppoted-httpd

**Comment by twystd** [comment]
Feature complete - will be included in release v0.8.3
