### ISSUE TITLE
Top level release build checksums should match project release checksums

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#20]
The checksums of the _uhppoted_ release build executables do not currently match the checksums of the executables produced by the release build of individual projects because the top level release build does not use `GO WORK=off`.

Rework the top level release build script:

- [x] Build with `GO WORK=off`
- [x] Verify _sha1sum_ of top-level release executables against project level release executables

Ref. https://github.com/uhppoted/uhppoted-tunnel/issues/7

**Comment by twystd** [comment]
Added SHA-256 checksum verification step to release script.
