### ISSUE TITLE
Include ARM64 binaries in releases

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#21]
Update all Makefiles to generate ARM64 binaries:

- ARM64 instances are generally available on Gooogle Cloud Run and AWS
- Raspberry Pi 4 is a 64 bit architecture

Modules:

- [x] uhppote-cli
- [x] uhppote-simulator
- [x] uhppoted-app-s3
- [x] uhppoted-app-sheets
- [x] uhppoted-app-wild-apricot
- [x] uhppoted-app-codegen
- [x] uhppoted-httpd
- [x] uhppoted-mqtt
- [x] uhppoted-rest
- [x] uhppoted-tunnel

**Comment by twystd** [comment]
Added ARM64 build to all release artificats (and removed _zip_ archive). Will be included in release v0.8.3.
