### ISSUE TITLE
Add top level package godoc for all modules

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#22]
Add top level godoc for each project:

- [x] uhppote-core
- [x] uhppoted-lib
- [x] uhppote-simulator
- [x] uhppote-cli
- [x] uhppoted-rest
- [x] uhppoted-mqtt
- [x] uhppoted-httpd
- [x] uhppoted-tunnel
- [x] uhppoted-codegen
- [x] uhppoted-dll
- [x] uhppoted-app-s3
- [x] uhppoted-app-sheets
- [x] uhppoted-app-wild-apricot

**Comment by twystd** [comment]
Closing - initial round of Go overview doc.go now in all projects.
