### ISSUE TITLE
Add govulncheck to all repos

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#27]
Add _govulncheck_:

- [x] _uhppote-core_
- [x] _uhppoted-lib_
- [x] _uhppote-simulator_
- [x] _uhppote-cli_
- [x] _uhppoted-rest_
- [x] _uhppoted-mqtt_
- [x] _uhppoted-tunnel_
- [x] _uhppoted-codegen_
- [x] _uhppoted-dll_
- [x] _uhppoted-httpd_
- [x] _uhppoted-app-s3_
- [x] _uhppoted-app-sheets_
- [x] _uhppoted-app-wild-apricot_
- [x] _uhppoted-app-db_

**Comment by twystd** [comment]
Added _vuln_ target all _Makefiles_ and included in _build-all_ target where feasible.
