### ISSUE TITLE
Implement activate-access-keypads function 

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#35]
Ref. https://github.com/uhppoted/uhppote-core/issues/16

Add support for the _Activate Access Keypad_ controller function (function code 0xA4):

- [x] uhppote-core
- [x] _uhppote-simulator_
- [x] _uhppoted-lib_
- [x] _uhppote-cli_
- [x] _uhppoted-rest_
- [x] _uhppoted-mqtt_
- [x] _uhppoted-codegen_
- [x] _uhppoted-dll_
- [x] _uhppoted-httpd_
- [x] _uhppoted-nodejs_
- [x] _node-red-contrib-uhppoted_
- [x] tasks: no password
- [x] tasks: in password
- [x] tasks: in/out password

**Comment by twystd** [comment]
Implemented across all modules - pending release v0.8.6
