### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#38]
### Docs
- https://developers.home-assistant.io
- https://developers.home-assistant.io/docs/development_index
- https://www.home-assistant.io/integrations/python_script
- https://www.home-assistant.io/docs/tools/dev-tools
- https://developers.home-assistant.io/docs/add-ons/tutorial/
- https://community.home-assistant.io/t/tutorial-for-creating-a-custom-component/204793
- https://appdaemon.readthedocs.io/en/latest/

### Examples
1. https://github.com/fuatakgun/eufy_security
2. https://github.com/vinteo/hass-opensprinkler
3. https://github.com/nordicopen/easee_hass
4. https://github.com/vlebourl/custom_vesync
5. https://github.com/topics/homeassistant-integration

### Notes

1. https://www.reddit.com/r/homeassistant/comments/t2w4z2/mqtt_access_control_integration
6. https://community.home-assistant.io/t/rfid-or-nfc-access-control/135835
7. https://community.home-assistant.io/t/access-control-a-comprehensive-standard-integration-into-the-core/420145
8. https://community.home-assistant.io/t/create-access-system-using-ha/286094
9. https://www.androidpolice.com/home-assistant-android-device-controls

**Comment by YBonline** [comment]
Just wanted to subscribe to this issue and was curious if you had any ETA? Thank you for all of your absolutely amazing work, can't wait for this!

**Comment by uhppoted** [comment]
Hey YB,

Nice to hear from you! 

I afraid there isn't an ETA as yet, mostly because I don't have even the vaguest clue as to what it's going to look like or what shape it's going to take. But the plan is to start once I've wrapped up the current tasks (about another week or so - so looking at beginning of November'ish). Unless it turns out to be particularly simple (ha! as if..) it's probably going to take a couple of months so don't hold your breath .. but we'll get there in the end :-).

**Comment by uhppoted** [comment]
Initial _alpha_ version released.
