### ISSUE TITLE
Prebuilt Docker containers

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#47]
Ref. [Issue #46: Docker Container](https://github.com/uhppoted/uhppoted/discussions/46)

- [x] _uhppoted.conf_ per container customization
- [x] ~~Dockerhub~~
- [x] [ghcr](https://github.blog/2020-09-01-introducing-github-container-registry)

Prebuilt Docker containers for:
- [x] _uhppoted-simulator_
- [x] _uhppoted-rest_
- [x] _uhppoted-mqtt_
- [x] _uhppoted-httpd_

Other:
- https://cloud.google.com/run (?)
- https://www.reddit.com/r/docker/comments/c3urip/what_is_a_cheap_or_even_free_way_of_hosting_a
- [nix](https://nixos.org) ??

**Comment by twystd** [comment]
First iteration of Docker container pushed to ghcr.io
