### ISSUE TITLE
Implement 'Restore Default Parameters' function

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#48]
`function code: 0xC8`

- [x] uhppote-core
- [x] uhppoted-lib
- [x] uhppote-simulator
- [x] uhppote-cli
- [x] uhppoted-rest
- [x] uhppoted-mqtt
- [x] uhppoted-codegen
- [x] uhppoted-dll
- [x] node-red-contrib-uhppoted
- [x] uhppoted-nodejs
- [x] uhppoted-python

cf. https://github.com/uhppoted/uhppoted-nodejs/issues/12

**Comment by twystd** [comment]
Closing - implemented across all modules. Scheduled for release with v0.8.8.
