### ISSUE TITLE
Update to Go v1.23

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted#53]
- [x] uhppote-core
- [x] uhppoted-lib
- [x] uhppote-simulator
- [x] uhppote-cli
- [x] uhppoted-rest
- [x] uhppoted-mqtt
- [x] uhppoted-httpd
- [x] uhppoted-codegen
- [x] uhppoted-dll
- [x] uhppoted-tunnel
- [x] uhppoted-app-s3
- [x] uhppoted-app-sheets
- [x] uhppoted-app-wild-apricot
- [x] uhppoted-app-db
- [x] uhppoted-breakout
- [x] uhppoted

**Comment by twystd** [comment]
Updated everything to Go 1.23.
